# Permalinks
permalink:        /post/:title
relative_permalinks: true

# Setup
title:            ID Laravel
tagline:          Tutorial Laravel Bahasa Indonesia
url:              https://djolie.github.io
relative_permalinks: true
paginate:         1
baseurl:          /
author:
  name:           Bayu Hendra Winata
  url:            https://twitter.com/uyab
  email:          uyab.exe@gmail.com

# Build options
exclude:          [node_modules]

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/id-laravel/id-laravel.github.io
